name: Update GitHub Contribution Snake

on:
  schedule:
    - cron: '0 0 * * *'  # cada día a medianoche UTC
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Generar el SVG con Platane/snk
      - uses: Platane/snk@v3
        with:
          github_user_name: toniGitH
          outputs: |
            dist/github-contribution-grid-snake.svg

      # Forzar que la carpeta dist exista y git pueda añadir el SVG
      - name: Prepare dist folder
        run: |
          mkdir -p dist
          if [ ! -f dist/github-contribution-grid-snake.svg ]; then
            touch dist/github-contribution-grid-snake.svg
          fi

      # Commit y push del SVG
      - name: Commit & Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update contribution snake" || echo "No changes to commit"
          git push
